#!/usr/bin/env python
import sys
import drqueue
import os

from BaseHTTPServer import HTTPServer
from CGIHTTPServer import CGIHTTPRequestHandler
from SocketServer import ForkingMixIn

class ForkingServer(ForkingMixIn,HTTPServer):
    pass

serveraddr = ('',8088)
server = ForkingServer(serveraddr, CGIHTTPRequestHandler)
server.serve_forever()
