# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "jobs", :force => true do |t|
    t.column "queue_id",   :integer
    t.column "renderer",   :string
    t.column "sort",       :string
    t.column "profile_id", :integer
  end

  create_table "profiles", :force => true do |t|
    t.column "name",         :string
    t.column "email",        :string
    t.column "avatar",       :string
    t.column "ldap_account", :string
    t.column "status",       :string
    t.column "accepted",     :integer, :default => 0
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

end
