
# 
# Copyright (C) 2001,2002,2003,2004,2005,2006 Jorge Daza Garcia-Blanes
#
# This file is part of DrQueue
# 
# DrQueue is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA	 02111-1307
# USA
# 
# $Id: /drqueue/remote/trunk/jobfinfo.c 2334 2005-07-05T03:50:01.502018Z jorge  $
#
# This program returns the number of times a frame has been requeued.
# Useful for avoiding endless loops
#

import sys
import glob
import os

env = Environment (CC = 'gcc', CCFLAGS=Split ('-DCOMM_REPORT -D_GNU_SOURCE -O2'), CPPFLAGS=Split ('-I.. -I../libdrqueue'))

swigflags = "-python -I.. -I../libdrqueue"

print "Platform is: ",sys.platform
if sys.platform == "linux2":
	env.Append (CCFLAGS = '-D__LINUX')
	env.Append (CPPPATH=['/usr/include/python2.4',"..","../libdrqueue"])
	swigflags = swigflags + " -D__LINUX"
elif sys.platform == "darwin":
	env.Append (CCFLAGS = Split('-D__OSX -fno-common'))
	env.Append (CPPPATH=['/sw/include/python2.4',"..","../libdrqueue"])
	env.Append (LIBS=['python2.4'],LIBPATH=['/sw/lib/python2.4/config'])
	swigflags = swigflags + " -D__OSX"


env.Append (CXXFLAGS='-D__CPLUSPLUS')
env.Append (SWIGFLAGS= Split(swigflags))

libdrqueue = glob.glob("../libdrqueue/*.c")

#
# libdrqueue.a
#
drqueue_i = glob.glob("*.i")
drqueue_all = drqueue_i + libdrqueue

env["SHLIBPREFIX"] = "_"
drqueue = env.SharedLibrary ("drqueue", drqueue_all)
#drqueue_copy = env.Command ("_drqueue.so",drqueue,"cp -f libdrqueue.so _drqueue.so")
#Depends(drqueue_copy,drqueue)
