import sys
import glob
import os

env = Environment (CC = 'gcc', CCFLAGS=Split ('-DCOMM_REPORT -D_GNU_SOURCE -O2'), CPPFLAGS=Split ('-I.. -I../libdrqueue'))

swigflags = "-python"

print "Platform is: ",sys.platform
if sys.platform == "linux2":
	env.Append (CCFLAGS = '-D__LINUX')
	env.Append (CPPPATH=['/usr/include/python2.4',"..","../libdrqueue"])
	swigflags = swigflags + " -D__LINUX"
elif sys.platform == "darwin":
	env.Append (CCFLAGS = Split('-D__OSX -fno-common'))
	env.Append (CPPPATH=['/sw/include/python2.4',"..","../libdrqueue"])
	env.Append (LIBS=['python2.4'],LIBPATH=['/sw/lib/python2.4/config'])
	swigflags = swigflags + " -D__OSX"


env.Append (CXXFLAGS='-D__CPLUSPLUS')
env.Append (SWIGFLAGS= Split(swigflags))

libdrqueue = glob.glob("../libdrqueue/*.c")

#
# libdrqueue.a
#
drqueue_i = glob.glob("*.i")
drqueue_all = drqueue_i + libdrqueue

env["SHLIBPREFIX"] = "_"
drqueue = env.SharedLibrary ("drqueue", drqueue_all)
#drqueue_copy = env.Command ("_drqueue.so",drqueue,"cp -f libdrqueue.so _drqueue.so")
#Depends(drqueue_copy,drqueue)
